#!/bin/bash

SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY:-$1}

if [ -z "${SSH_PRIVATE_KEY}" ]; then
    echo "Usage: load_ssh_private_key <SSH_PRIVATE_KEY>"
    exit 1
fi

mkdir -p ~/.ssh
chmod 700 ~/.ssh
echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa
